before_install:
  - git clone --quiet --depth 1 https://github.com/vim-jp/vim.git vim
  - cd vim
  - ./configure --prefix=$PWD/build --with-features=huge --enable-multibyte
  - make
  - make install
  - export PATH=$PWD/build/bin:$PATH
  - cd ..

before_script:
  - vim --version

script:
  - ./bin/themis --reporter dot
