language: generic

env:
  - HEAD=yes
  - HEAD=no

sudo: false

addons:
  apt:
    packages:
      - language-pack-ja
      - vim
      - libperl-dev
      - python-dev
      - python3-dev
      - liblua5.1-0-dev
      - lua5.1

install:
  - |
    if [ x"$HEAD" = "xyes" ]; then
      git clone --depth 1 --single-branch https://github.com/vim/vim /tmp/vim
      cd /tmp/vim
      ./configure --prefix="$HOME/vim" --with-features=huge \
        --enable-perlinterp --enable-pythoninterp --enable-python3interp \
        --enable-rubyinterp --enable-luainterp --enable-fail-if-missing
      make -j2
      make install
      export PATH=$HOME/vim/bin:$PATH
      cd "${TRAVIS_BUILD_DIR}"
    fi

script:
  - vim --version
  - ./bin/themis --reporter dot
