before_install:
  - git clone --quiet --single-branch --depth 1 https://github.com/vim-jp/vim.git /tmp/vim
  - cd /tmp/vim
  - ./configure --prefix=$PWD/build --with-features=huge --enable-multibyte
  - make
  - make install
  - export PATH=$PWD/build/bin:$PATH
  - cd -

  - git clone https://github.com/thinca/vim-themis --quiet --branch v1.4 --single-branch --depth 1 /tmp/vim-themis

before_script:
  - vim --version

script:
  - /tmp/vim-themis/bin/themis --reporter dot
